version: 2
defaults: &defaults
  working_directory: ~/ionicapp
  docker:
    - image: trkrakesh/nah-angular
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
            name: "Setup Environment Variables"
            command: |
              echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
              echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
      - run: export TERM=xterm && ./gradlew androidDepedencies
      - run:
            name: "Install npm packages"
            command: |
              cd nah-mobile && npm install
      - run:
            name: "Install Cordova plugins and add android platform"
            command: |
              cd nah-mobile && ionic cordova build --prod  android  --verbose --release
      - run:
            name: "Generate apk"
            command: |
              mkdir -p /tmp/apk && cd nah-mobile && cp -r platforms/android/app/build/outputs/apk/ /tmp/apk
      - run:
            name: "Keysotr build"
            command: |
              cd nah-mobile && keytool -list -v -keystore keys/android/nah.keystore -alias key0 -storepass nahnah -keypass nahnah
           
      - store_artifacts:
            path: /tmp/apk
            destination: apks

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
