version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/android:api-29-node
  environment:
    JVM_OPTS: -Xmx3200m

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e0:f1:4e:cf:33:92:dd:d4:2a:4e:0f:de:fb:11:d6:08"
      - run:
            name: "Setup Environment Variables"
            command: |
              echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
              echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
      - run: 
          name: "Install gradle"
          command: |
              wget https://services.gradle.org/distributions/gradle-6.5.1-bin.zip -P /tmp
              sudo unzip -d /opt/gradle /tmp/gradle-*.zip
              echo 'export GRADLE_HOME=/opt/gradle/gradle-6.5.1' >> $BASH_ENV
              echo 'export PATH=$PATH:/opt/gradle/gradle-6.5.1/bin' >> $BASH_ENV
              source $BASH_ENV
      - run:
            name: "move nah mobile folder"
            command: |
              cd nah-mobile
      - run:
            name: "Install ionic and cordova"
            command: |
              sudo npm install -g ionic cordova node-gyp
      - run:
            name: "Install npm packages"
            command: |
              cd nah-mobile && yarn install
      - run:
            name: "Install Cordova plugins and add android platform"
            command: |
              cd nah-mobile && ionic cordova platform add android@^9.0.0 --verbose
              ionic config set -g telemetry true
      - run:
            name: "Generate apk"
            command: |
              cd nah-mobile && ionic cordova build --prod  android  --verbose -- --keystore=keys/android/nah.keystore --storePassword=nahnah --alias=key0 --password=nahnah
              mkdir -p /tmp/apk
              cp -r platforms/android/app/build/outputs/apk/ /tmp/apk
      - run:
            name: "Keysotr build"
            command: |
              cd nah-mobile && keytool -list -v -keystore keys/android/nah.keystore -alias key0 -storepass nahnah -keypass nahnah
           
      - store_artifacts:
            path: /tmp/apk
            destination: apks

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
