version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: dmastag/alpine-node-openjdk-android-cordova
  environment:
    JVM_OPTS: -Xmx3200m
    GRADLE_VERSION: 6.5.1
    CORDOVA_VERSION: 9.0.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
            name: "Setup Environment Variables"
            command: |
              echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
              echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV

      - run:
            name: "move nah mobile folder"
            command: |
              cd nah-mobile
      - run:
            name: "Install ionic and cordova"
            command: |
              sudo npm install -g ionic node-gyp
      - run:
            name: "Install npm packages"
            command: |
              cd nah-mobile && yarn install
      - run:
            name: "versions"
            command: |
              ionic --version && cordova --version && gradle --version
      - run:
            name: "Install Cordova plugins and add android platform"
            command: |
              cd nah-mobile && ionic cordova platform add android@^9.0.0 --verbose
              ionic config set -g telemetry true
      - run:
            name: "Generate apk"
            command: |
              cd nah-mobile && ionic cordova build --prod  android  --verbose -- --keystore=keys/android/nah.keystore --storePassword=nahnah --alias=key0 --password=nahnah
              mkdir -p /tmp/apk
              cp -r platforms/android/app/build/outputs/apk/ /tmp/apk
      - run:
            name: "Keysotr build"
            command: |
              cd nah-mobile && keytool -list -v -keystore keys/android/nah.keystore -alias key0 -storepass nahnah -keypass nahnah
           
      - store_artifacts:
            path: /tmp/apk
            destination: apks

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
